// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.

// More resources in https://jakearchibald.com/2014/offline-cookbook/
// http://www.actminds.com/blog/pwa/

var CACHE_NAME = 'gdg-intial-v.0.0.2'

var files = [
	"index.html",
	"favicon.ico",
	"manifest.json",
	"manifest.webapp",
	"scripts/main.min.js",
	"styles/main.css",
	"images/bg.jpg",
	"images/bg1.jpg",
	"images/drawer-logo.png",
	"images/hamburger.svg",
	"images/logo.png",
	"images/industries/gcp.jpg",
	"images/industries/hbp.jpg",
	"images/industries/ulc.jpg",
	"images/organizers/photo.jpg",
	"images/institutions/iim-k.jpg",
	"images/institutions/nit-c.jpg",
	"images/institutions/nit-c2.png",
	"images/touch/apple-touch-icon.png",
	"images/touch/chrome-touch-icon-192x192.png",
	"images/touch/icon-128x128.png",
	"images/touch/icon-256x256.png",
	"images/touch/icon-512x512.png",
	"images/touch/ms-touch-icon-144x144-precomposed.png",
	"images/supporters/gcp.jpg",
	"images/supporters/google.svg",
	"images/supporters/iim-k.png",
	"images/supporters/ksidc.png",
	"images/supporters/ulcp.png",
	"images/supporters/ksum.jpg",
	"images/supporters/nasscom.jpg",
	"images/supporters/nit-c.jpg",
];

self.addEventListener('install', function(event){
	event.waitUntil(
		caches.open(CACHE_NAME).then(function(cache){
			return Promise.all(
				files.map(function(file){
					return cache.add(file);
				}));
		}));
});
